# Generated by Django 3.0.8 on 2020-07-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheese',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=255, verbose_name='Country of Origin'),
        ),
    ]
